### PR TITLE
Adding revised git commit structure

### PR DESCRIPTION
**Pull request by rbvea**
Added brief description of the article in slack.
Also added the screenshot of gitx which has guidelines for the 50/72 style.

Github issue #1

### CODE REVIEW

**Comment by nateluzod** [comment]
@rbvea can you add some text around the possible commands that can go into the commit message?

Right now I think there's `fixes`, `finishes` and `delivers`. 

https://www.pivotaltracker.com/help/api?version=v3#scm_post_commit_message_syntax

**Comment by rbvea** [comment]
@nateluzod done, guess I was using the wrong post-commit structure before.  Thanks for pointing that out.   @tommyokeefe any objections?

**Comment by tommyokeefe** [comment]
Sounds good to me.

**Comment by nateluzod** [comment]
@rbvea looks good to me. Safe to merge.

**Pull request merged**
